paper_main:
    resource: "@PaperMainBundle/Controller/"
    type:     annotation
    prefix:   /

_security_login:
    pattern:  /login
    defaults: { _controller: PaperMainBundle:Auth:login }

login_check:
    path: /login_check

_security_logout:
    pattern:  /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"